{"uid":"1bfc95b336c9465a","name":"test_select_one","fullName":"tests.integration.dbapi.sync.test_system_engine#test_select_one","historyId":"493b0aaae61994fbf6f0650f8187bd34","time":{"start":1682612043616,"stop":1682612043690,"duration":74},"description":"SELECT statements are supported","descriptionHtml":"<p>SELECT statements are supported</p>\n","status":"broken","statusMessage":"firebolt.utils.exception.OperationalError: Error executing query:\nReceived error from remote server /core/v1/accounts/15ff9dd6-32a6-417b-b004-6f69d7cc4c8b/engines:getIdByName?engine_name=integration_testing__1682611178_system_test. HTTP status code: 400 Bad Request, body: {\"error\":\"failed to process resource reference engine:\\\"integration_testing__1682611178_system_test\\\": failed to resolve resource name to ID: invalid engine resource, can't resolve engine resource name integration_testing__1682611178_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"code\":3,\"message\":\"failed to process resource reference engine:\\\"integration_testing__1682611178_system_test\\\": failed to resolve resource name to ID: invalid engine resource, can't resolve engine resource name integration_testing__1682611178_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"details\":[]}","statusTrace":"connection_system_engine = <firebolt.db.connection.Connection object at 0x7f01f1798550>\ndb_name = 'integration_testing__1682611178_system_test'\nsecond_db_name = 'integration_testing__1682611178_system_test_two'\nengine_name = 'integration_testing__1682611178_system_test'\nregion = 'us-east-1'\n\n    @fixture(scope=\"module\")\n    def setup_dbs(connection_system_engine, db_name, second_db_name, engine_name, region):\n        with connection_system_engine.cursor() as cursor:\n    \n            cursor.execute(create_database(name=db_name))\n    \n            cursor.execute(create_engine(engine_name, engine_specs(region)))\n    \n            cursor.execute(\n                create_database(name=second_db_name, specs=db_specs(region, engine_name))\n            )\n    \n            yield\n    \n>           cursor.execute(f\"DROP ENGINE IF EXISTS {engine_name}\")\n\ntests/integration/dbapi/sync/test_system_engine.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/db/cursor.py:54: in execute\n    query, parameters, skip_parsing, async_execution\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/utils/util.py:85: in sync\n    return trio.run(partial(f, *args, **kwargs))\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:526: in execute\n    await self._do_execute(query, params_list, skip_parsing, async_execution)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:474: in _do_execute\n    await self._raise_if_error(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <firebolt.db.cursor.Cursor object at 0x7f01f92bfdd0>\nresp = <Response [500 Internal Server Error]>\n\n    async def _raise_if_error(self, resp: Response) -> None:\n        \"\"\"Raise a proper error if any\"\"\"\n        if resp.status_code == codes.INTERNAL_SERVER_ERROR:\n            raise OperationalError(\n>               f\"Error executing query:\\n{resp.read().decode('utf-8')}\"\n            )\nE           firebolt.utils.exception.OperationalError: Error executing query:\nE           Received error from remote server /core/v1/accounts/15ff9dd6-32a6-417b-b004-6f69d7cc4c8b/engines:getIdByName?engine_name=integration_testing__1682611178_system_test. HTTP status code: 400 Bad Request, body: {\"error\":\"failed to process resource reference engine:\\\"integration_testing__1682611178_system_test\\\": failed to resolve resource name to ID: invalid engine resource, can't resolve engine resource name integration_testing__1682611178_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"code\":3,\"message\":\"failed to process resource reference engine:\\\"integration_testing__1682611178_system_test\\\": failed to resolve resource name to ID: invalid engine resource, can't resolve engine resource name integration_testing__1682611178_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"details\":[]}\n\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:259: OperationalError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"username","time":{"start":1682611398275,"stop":1682611398275,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"password_auth","time":{"start":1682611398276,"stop":1682611398590,"duration":314},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"password","time":{"start":1682611398276,"stop":1682611398276,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"api_endpoint","time":{"start":1682611398590,"stop":1682611398591,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"account_name","time":{"start":1682611399076,"stop":1682611399076,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"connection_system_engine","time":{"start":1682611426011,"stop":1682611426234,"duration":223},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"SELECT statements are supported","status":"broken","statusMessage":"firebolt.utils.exception.OperationalError: Error executing query:\nReceived error from remote server /core/v1/accounts/15ff9dd6-32a6-417b-b004-6f69d7cc4c8b/engines:getIdByName?engine_name=integration_testing__1682611178_system_test. HTTP status code: 400 Bad Request, body: {\"error\":\"failed to process resource reference engine:\\\"integration_testing__1682611178_system_test\\\": failed to resolve resource name to ID: invalid engine resource, can't resolve engine resource name integration_testing__1682611178_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"code\":3,\"message\":\"failed to process resource reference engine:\\\"integration_testing__1682611178_system_test\\\": failed to resolve resource name to ID: invalid engine resource, can't resolve engine resource name integration_testing__1682611178_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"details\":[]}","statusTrace":"connection_system_engine = <firebolt.db.connection.Connection object at 0x7f01f1798550>\ndb_name = 'integration_testing__1682611178_system_test'\nsecond_db_name = 'integration_testing__1682611178_system_test_two'\nengine_name = 'integration_testing__1682611178_system_test'\nregion = 'us-east-1'\n\n    @fixture(scope=\"module\")\n    def setup_dbs(connection_system_engine, db_name, second_db_name, engine_name, region):\n        with connection_system_engine.cursor() as cursor:\n    \n            cursor.execute(create_database(name=db_name))\n    \n            cursor.execute(create_engine(engine_name, engine_specs(region)))\n    \n            cursor.execute(\n                create_database(name=second_db_name, specs=db_specs(region, engine_name))\n            )\n    \n            yield\n    \n>           cursor.execute(f\"DROP ENGINE IF EXISTS {engine_name}\")\n\ntests/integration/dbapi/sync/test_system_engine.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/db/cursor.py:54: in execute\n    query, parameters, skip_parsing, async_execution\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/utils/util.py:85: in sync\n    return trio.run(partial(f, *args, **kwargs))\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:526: in execute\n    await self._do_execute(query, params_list, skip_parsing, async_execution)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:474: in _do_execute\n    await self._raise_if_error(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <firebolt.db.cursor.Cursor object at 0x7f01f92bfdd0>\nresp = <Response [500 Internal Server Error]>\n\n    async def _raise_if_error(self, resp: Response) -> None:\n        \"\"\"Raise a proper error if any\"\"\"\n        if resp.status_code == codes.INTERNAL_SERVER_ERROR:\n            raise OperationalError(\n>               f\"Error executing query:\\n{resp.read().decode('utf-8')}\"\n            )\nE           firebolt.utils.exception.OperationalError: Error executing query:\nE           Received error from remote server /core/v1/accounts/15ff9dd6-32a6-417b-b004-6f69d7cc4c8b/engines:getIdByName?engine_name=integration_testing__1682611178_system_test. HTTP status code: 400 Bad Request, body: {\"error\":\"failed to process resource reference engine:\\\"integration_testing__1682611178_system_test\\\": failed to resolve resource name to ID: invalid engine resource, can't resolve engine resource name integration_testing__1682611178_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"code\":3,\"message\":\"failed to process resource reference engine:\\\"integration_testing__1682611178_system_test\\\": failed to resolve resource name to ID: invalid engine resource, can't resolve engine resource name integration_testing__1682611178_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"details\":[]}\n\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:259: OperationalError","steps":[],"attachments":[{"uid":"d2779ecea3233b21","name":"log","source":"d2779ecea3233b21.txt","type":"text/plain","size":99}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"connection_system_engine::0","time":{"start":1682612079069,"stop":1682612079070,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"xdist_group(name='system_engine')"},{"name":"parentSuite","value":"tests.integration.dbapi.sync"},{"name":"suite","value":"test_system_engine"},{"name":"host","value":"fv-az1236-303"},{"name":"thread","value":"2543-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.dbapi.sync.test_system_engine"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["xdist_group(name='system_engine')"]},"source":"1bfc95b336c9465a.json","parameterValues":[]}