{"uid":"6e1f48706999ecc9","name":"test_select_one","fullName":"tests.integration.dbapi.sync.test_system_engine#test_select_one","historyId":"493b0aaae61994fbf6f0650f8187bd34","time":{"start":1682609926266,"stop":1682609926384,"duration":118},"description":"SELECT statements are supported","descriptionHtml":"<p>SELECT statements are supported</p>\n","status":"broken","statusMessage":"firebolt.utils.exception.OperationalError: Error executing query:\nReceived error from remote server /core/v1/accounts/15ff9dd6-32a6-417b-b004-6f69d7cc4c8b/databases:getIdByName?database_name=integration_testing__1682609139_system_test. HTTP status code: 400 Bad Request, body: {\"error\":\"failed to process resource reference database:\\\"integration_testing__1682609139_system_test\\\": failed to resolve resource name to ID: invalid database resource, can't resolve database resource name integration_testing__1682609139_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"code\":3,\"message\":\"failed to process resource reference database:\\\"integration_testing__1682609139_system_test\\\": failed to resolve resource name to ID: invalid database resource, can't resolve database resource name integration_testing__1682609139_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"details\":[]}","statusTrace":"connection_system_engine = <firebolt.db.connection.Connection object at 0x7f23e06a02d0>\ndb_name = 'integration_testing__1682609139_system_test'\nsecond_db_name = 'integration_testing__1682609139_system_test_two'\nengine_name = 'integration_testing__1682609139_system_test'\nregion = 'us-east-1'\n\n    @fixture(scope=\"module\")\n    def setup_dbs(connection_system_engine, db_name, second_db_name, engine_name, region):\n        with connection_system_engine.cursor() as cursor:\n    \n            cursor.execute(create_database(name=db_name))\n    \n            cursor.execute(create_engine(engine_name, engine_specs(region)))\n    \n            cursor.execute(\n                create_database(name=second_db_name, specs=db_specs(region, engine_name))\n            )\n    \n            yield\n    \n            cursor.execute(f\"DROP ENGINE IF EXISTS {engine_name}\")\n>           cursor.execute(f\"DROP DATABASE IF EXISTS {db_name}\")\n\ntests/integration/dbapi/sync/test_system_engine.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/db/cursor.py:54: in execute\n    query, parameters, skip_parsing, async_execution\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/utils/util.py:85: in sync\n    return trio.run(partial(f, *args, **kwargs))\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:526: in execute\n    await self._do_execute(query, params_list, skip_parsing, async_execution)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:474: in _do_execute\n    await self._raise_if_error(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <firebolt.db.cursor.Cursor object at 0x7f23e0a06cb0>\nresp = <Response [500 Internal Server Error]>\n\n    async def _raise_if_error(self, resp: Response) -> None:\n        \"\"\"Raise a proper error if any\"\"\"\n        if resp.status_code == codes.INTERNAL_SERVER_ERROR:\n            raise OperationalError(\n>               f\"Error executing query:\\n{resp.read().decode('utf-8')}\"\n            )\nE           firebolt.utils.exception.OperationalError: Error executing query:\nE           Received error from remote server /core/v1/accounts/15ff9dd6-32a6-417b-b004-6f69d7cc4c8b/databases:getIdByName?database_name=integration_testing__1682609139_system_test. HTTP status code: 400 Bad Request, body: {\"error\":\"failed to process resource reference database:\\\"integration_testing__1682609139_system_test\\\": failed to resolve resource name to ID: invalid database resource, can't resolve database resource name integration_testing__1682609139_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"code\":3,\"message\":\"failed to process resource reference database:\\\"integration_testing__1682609139_system_test\\\": failed to resolve resource name to ID: invalid database resource, can't resolve database resource name integration_testing__1682609139_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"details\":[]}\n\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:259: OperationalError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"username","time":{"start":1682609328772,"stop":1682609328773,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"password_auth","time":{"start":1682609328773,"stop":1682609329064,"duration":291},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"password","time":{"start":1682609328773,"stop":1682609328773,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"api_endpoint","time":{"start":1682609329065,"stop":1682609329065,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"account_name","time":{"start":1682609329468,"stop":1682609329469,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"connection_system_engine","time":{"start":1682609353872,"stop":1682609354276,"duration":404},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"SELECT statements are supported","status":"broken","statusMessage":"firebolt.utils.exception.OperationalError: Error executing query:\nReceived error from remote server /core/v1/accounts/15ff9dd6-32a6-417b-b004-6f69d7cc4c8b/databases:getIdByName?database_name=integration_testing__1682609139_system_test. HTTP status code: 400 Bad Request, body: {\"error\":\"failed to process resource reference database:\\\"integration_testing__1682609139_system_test\\\": failed to resolve resource name to ID: invalid database resource, can't resolve database resource name integration_testing__1682609139_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"code\":3,\"message\":\"failed to process resource reference database:\\\"integration_testing__1682609139_system_test\\\": failed to resolve resource name to ID: invalid database resource, can't resolve database resource name integration_testing__1682609139_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"details\":[]}","statusTrace":"connection_system_engine = <firebolt.db.connection.Connection object at 0x7f23e06a02d0>\ndb_name = 'integration_testing__1682609139_system_test'\nsecond_db_name = 'integration_testing__1682609139_system_test_two'\nengine_name = 'integration_testing__1682609139_system_test'\nregion = 'us-east-1'\n\n    @fixture(scope=\"module\")\n    def setup_dbs(connection_system_engine, db_name, second_db_name, engine_name, region):\n        with connection_system_engine.cursor() as cursor:\n    \n            cursor.execute(create_database(name=db_name))\n    \n            cursor.execute(create_engine(engine_name, engine_specs(region)))\n    \n            cursor.execute(\n                create_database(name=second_db_name, specs=db_specs(region, engine_name))\n            )\n    \n            yield\n    \n            cursor.execute(f\"DROP ENGINE IF EXISTS {engine_name}\")\n>           cursor.execute(f\"DROP DATABASE IF EXISTS {db_name}\")\n\ntests/integration/dbapi/sync/test_system_engine.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/db/cursor.py:54: in execute\n    query, parameters, skip_parsing, async_execution\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/utils/util.py:85: in sync\n    return trio.run(partial(f, *args, **kwargs))\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:526: in execute\n    await self._do_execute(query, params_list, skip_parsing, async_execution)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:474: in _do_execute\n    await self._raise_if_error(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <firebolt.db.cursor.Cursor object at 0x7f23e0a06cb0>\nresp = <Response [500 Internal Server Error]>\n\n    async def _raise_if_error(self, resp: Response) -> None:\n        \"\"\"Raise a proper error if any\"\"\"\n        if resp.status_code == codes.INTERNAL_SERVER_ERROR:\n            raise OperationalError(\n>               f\"Error executing query:\\n{resp.read().decode('utf-8')}\"\n            )\nE           firebolt.utils.exception.OperationalError: Error executing query:\nE           Received error from remote server /core/v1/accounts/15ff9dd6-32a6-417b-b004-6f69d7cc4c8b/databases:getIdByName?database_name=integration_testing__1682609139_system_test. HTTP status code: 400 Bad Request, body: {\"error\":\"failed to process resource reference database:\\\"integration_testing__1682609139_system_test\\\": failed to resolve resource name to ID: invalid database resource, can't resolve database resource name integration_testing__1682609139_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"code\":3,\"message\":\"failed to process resource reference database:\\\"integration_testing__1682609139_system_test\\\": failed to resolve resource name to ID: invalid database resource, can't resolve database resource name integration_testing__1682609139_system_test for account id 15ff9dd6-32a6-417b-b004-6f69d7cc4c8b to id: no rows in result set\",\"details\":[]}\n\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/firebolt/async_db/cursor.py:259: OperationalError","steps":[],"attachments":[{"uid":"58d6f65f4f8e521b","name":"log","source":"58d6f65f4f8e521b.txt","type":"text/plain","size":200}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"connection_system_engine::0","time":{"start":1682609965261,"stop":1682609965263,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"xdist_group(name='system_engine')"},{"name":"parentSuite","value":"tests.integration.dbapi.sync"},{"name":"suite","value":"test_system_engine"},{"name":"host","value":"fv-az389-439"},{"name":"thread","value":"2552-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.dbapi.sync.test_system_engine"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["xdist_group(name='system_engine')"]},"source":"6e1f48706999ecc9.json","parameterValues":[]}